name: Main

on:
  push:
    # paths:
    #  - '**.md'
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/checkout@v2

      - run: npm install

      # - id: foo
      #  uses: ./.github/actions/homebrewery
      #  with:
      #    filename: witchcraft_fr
      
      - run: npm run hb -- witchcraft_fr.md witchcraft_fr.pdf

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Preview"
          files: *.pdf



